export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';

export const UPDATE_SEARCH_FORM_SUCCESS = 'UPDATE_SEARCH_FORM_SUCCESS';

export const UPDATE_ERRORS_SUCCESS = 'UPDATE_ERRORS_SUCCESS';

export const CLEAR_ERRORS_DISPLAY_SUCCESS = 'CLEAR_ERRORS_DISPLAY_SUCCESS';

export const DELETE_ERRORS_SUCCESS = 'DELETE_ERRORS_SUCCESS';

export const UPDATE_AJAX_CALLS_SUCCESS = 'UPDATE_AJAX_CALLS_SUCCESS';
